name = "PhyloCoalSimulations"
uuid = "53f7b83a-06b5-4910-9a21-1896bf762ade"
authors = ["Cecile Ane <cecileane@users.noreply.github.com>",
           "John Fogg <70609062+fogg-uw@users.noreply.github.com>"]
version = "0.1.2"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"

[compat]
Distributions = "0.25"
PhyloNetworks = "0.16"
julia = "1.5"
