name = "PhyloCoalSimulations"
uuid = "53f7b83a-06b5-4910-9a21-1896bf762ade"
authors = ["Cecile Ane <cecileane@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
